apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: mikeluo777/book-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: bookreviewhub-secrets
                  key: POSTGRES_DB
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: bookreviewhub-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookreviewhub-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: ClusterIP
  ports:
    - port: 5002
  selector:
    app: book-service
