apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: mikeluo777/gateway-service:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
  #type: NodePort
  #ports:
  #- name: http 
  #  port: 5000           # The port on the service
  #    targetPort: 5000      # The port the container listens on
  #    nodePort: 30000       # The external port on the node (can be any port in the range 30000-32767)
  #    protocol: TCP
  selector:
    app: gateway-service
